export const GET_PRODUCTOS_SUCCES = "GET_PRODUCTOS_SUCCES";
export const GET_PRODUCTOS_FAIL = "GET_PRODUCTOS_FAIL";
export const GET_PRODUCTOS_DETAIL_SUCCES = "GET_PRODUCTOS_DETAIL_SUCCES";
export const GET_PRODUCTOS_DETAIL_FAIL = "GET_PRODUCTOS_DETAIL_FAIL";
