export const GET_CATEGORIAS_SUCCES = 'GET_CATEGORIAS_SUCCES';
export const GET_CATEGORIAS_FAIL = 'GET_CATEGORIAS_FAIL';

export const GET_CATEGORIAS_DETAIL_SUCCES = 'GET_CATEGORIAS_DETAIL_SUCCES';
export const GET_CATEGORIAS_DETAIL_FAIL = 'GET_CATEGORIAS_DETAIL_FAIL';