export const GET_MARCAS_SUCCES = 'GET_MARCAS_SUCCES';
export const GET_MARCAS_FAIL = 'GET_MARCAS_FAIL';

export const GET_MARCAS_DETAIL_SUCCES = 'GET_MARCAS_DETAIL_SUCCES';
export const GET_MARCAS_DETAIL_FAIL = 'GET_MARCAS_DETAIL_FAIL';