export const GET_SUBCATEGORIAS_SUCCES = "GET_SUBCATEGORIAS_SUCCES";
export const GET_SUBCATEGORIAS_FAIL = "GET_SUBCATEGORIAS_FAIL";

export const GET_SUBCATEGORIAS_DETAIL_SUCCES =
  "GET_SUBCATEGORIAS_DETAIL_SUCCES";
export const GET_SUBCATEGORIAS_DETAIL_FAIL = "GET_SUBCATEGORIAS_DETAIL_FAIL";
